### PR TITLE
Merging app interface and logic with development branch

### PR DESCRIPTION
**Pull request by ggotora**
## What?
Code for creating a event creation app with login feature in rails framework. This has the functional code with a model. controller and views for user to create and edit a user with necessary validations.  
## Why?
As a part of learning rails to build a full stack webapp .
## How?
Mentioned in Readme 
## Testing?
Can be tested using the local host and instructions given in readme. 

Changes made after the review: 

- [x] You should make all the navigation link at the top of the page for easier browsing
- [x] Kindly fix the logout method because it doesn't seem to work fine. Think about the session controller and how you're gonna end a particular session.
- [x] When I create an event, it doesn't make sense to show the Attend button to attend that event (Creators should be attending their events by default because they're the owners) Kindly fix this issue
- [x] When I create an event, it suppose to show up on both the events index page and the user show page (whether it's an upcoming event or a past one.)
- [x] Kindly attach the ```rails db:create``` CLI step before the ```rails db:migrate``` one in your README file.
- [x] Add unit tests for your models, authentication that you've built, and the event management system you've built as well.
- [x] Please remove any related logic from your views and use the helpers to do that matter.

Changes made after the 2nd review:

- [x] An `index` for `creator_id` column should be added.
- [x] An `index` for `attendee_id` column should be added.
- [x] An `index` for `attended_event_id` column should be added.
- [x] Create separate folders for each kind of tests (Models/Features)
- [x] Delete all comments.
- [x] Please remove any related logic from your views by using `helpers` _(not partial)_ .
- [x] Check the use of session it seems not working. (Works perfectly well for first tse as well)

Changes after the 3rd review

- [x] Add Foreign Keys to schema
image

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great job you've done so far on this app. Your database connections are all set up very well, a decent README file, and descriptive commit messages. However, there are still a few more changes to make in order to get it approved. 😊🙏

- [x] You should make all the navigation link at the top of the page for easier browsing
navigation_links_requirement

- [x] Kindly fix the logout method because it doesn't seem to work fine. Think about the session controller and how you're gonna end a particular session.
- [x] When I create an event, it doesn't make sense to show the Attend button to attend that event (Creators should be attending their events by default because they're the owners) Kindly fix this issue
- [x] When I create an event, it suppose to show up on both the events index page and the user show page (whether it's an upcoming event or a past one.)
- [x] Kindly attach the ```rails db:create``` CLI step before the ```rails db:migrate``` one in your README file.
- [x] Add unit tests for your models, authentication that you've built, and the event management system you've built as well.
integration_tests_requirement
unit_tests_requirement

- [x] Please remove any related logic from your views and use the helpers to do that matter.

<hr>

## **[OPTIONAL]**

- I suggest styling your app a little bit for easier understanding and interacting
- I suggest deploying the app on a live demo link i.e. Heroku for easier access

<hr>

Kindly do the above changes and ask for another review 😊🙏
Good luck and happy coding 👨‍💻💻

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Hello Team :wave:
Status: Changes Required :recycle:

Good job on using `shoulda-matchers` and trying to work on previous TSE recommendations.
But before approving this project let's cover a few details together to make your project better :blush: :arrow_double_down: . I am sure that it will not take a lot of time:

REQUIRED:
- [x] An `index` for `creator_id` column should be added.
- [x] An `index` for `attendee_id` column should be added.
- [x] An `index` for `attended_event_id` column should be added.
- [x] Create separate folders for each kind of tests (Models/Features)
- [x] Delete all comments.
- [x] Please remove any related logic from your views by using `helpers` _(not partial)_ .
- [x] Check the use of session it seems not working.

That's it, you can submit another code review request after making these changes
With all my respect :pray:

Rindra Josia

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi team!
Great job so far on this project. And well done on implementing most of the changes requested by the previous Tse's. The app is working as expected:clap::clap:. However, we just need to make a few changes to get the project approved:muscle:.**

**Mandatory requirements**
Database foreign keys and indexes ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/foreign_key_index_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [x] the events_attendation/events_users/(any other name for join table between users and events) table has column `event_id` of type `integer`

- [x] an index for `event_id` column is added

- [x] the events_attendation/events_users/(any other name for join table between users and events) table has column `user_id` of type `integer`

- [x] an index for `user_id` column is added

Why indices for foreign keys are necessary? In short: Since the foreign key columns will be used often to retrieve related information, it's important to index them (queries on those columns will be faster with indexes). More details:
Check [here](https://semaphoreci.com/blog/2017/05/09/faster-rails-is-your-database-properly-indexed.html) and [here](https://sqlperformance.com/2012/11/t-sql-queries/benefits-indexing-foreign-keys.)

Make the above required changes and when you are ready, request another review.
Kindly drop your questions:point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan.

**Review by andresporras3423 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello Akshay Narkar & Gilbert Gotora** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the development branch
 
Keep going like this  :clap: :clap:
 
Oscar Andrés Russi Porras

**Pull request merged**
